version: "3.1"
services:
    app:
        container_name: ${CONTAINER_NAME}
        build: ${BUILD_PATH}
        restart: always
        ports:
          - ${HOST_PORT}:${CONTAINER_PORT}
        volumes:
          - ${HOST_PATH}:${CONTAINER_PATH}